#!/usr/bin/env php
<?php
// wrapper for the tools in the "shell" subfolder
if (!(php_sapi_name() === 'cli' or defined('STDIN'))) {
    header("HTTP/1.0 403 Forbidden");
    echo "This is a command line only script.";
    exit();
}

echo "This tool is obsolete use vendor/bin/robo instead to execute CLI tasks";
