CREATE TABLE IF NOT EXISTS `{prefix}content` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`systemname` varchar(255) NOT NULL,
`title` varchar(255) NOT NULL,
`alternate_title` VARCHAR(255) DEFAULT '',
`target` varchar(255) DEFAULT '_self',
`category` int(11) DEFAULT '1',
`content` longtext NOT NULL,
`language` varchar(6) NOT NULL,
`menu_image` varchar(255) NULL,
`active` tinyint(1) NOT NULL,
`created` bigint(20) NOT NULL,
`lastmodified` bigint(20) NOT NULL,
`autor` int(11) NULL,
`lastchangeby` int(11) NOT NULL,
`views` int(11) NOT NULL,
`comments_enabled` tinyint(1) NOT NULL,
`redirection` varchar(255) NOT NULL,
`menu` varchar(10) NOT NULL,
`position` int(11) NOT NULL,
`parent` int(11) DEFAULT NULL,
`access` varchar(100) DEFAULT NULL,
`meta_description` text NOT NULL,
`meta_keywords` text NOT NULL,
`deleted_at` bigint(20) DEFAULT NULL,
`html_file` varchar(255) DEFAULT NULL,
`theme` varchar(200) null,
`custom_data` varchar(255) NULL DEFAULT '{}',
`type` varchar(50) DEFAULT 'page' NULL,
`og_title` varchar(255) DEFAULT '',
`og_type` varchar(255) DEFAULT '',
`og_image` varchar(255) DEFAULT '',
`og_description` varchar(255) DEFAULT '',
`module` varchar(200) default null,
`video` int(11) default null,
`audio` int(11) default null,
`text_position` varchar(10) default 'before',
`approved` tinyint(1) NOT NULL DEFAULT '1',
`image_url` text default null,
`show_headline` tinyint(1) NOT NULL DEFAULT '1',
PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=22 ;
